language: java

jdk:
  - openjdk8
  - oraclejdk8

branches:
  only:
  - master

dist: xenial

sudo: required

before_install:
  - sudo apt update

install:
  - sudo apt install maven -y

before_script: 
  - cd project
  - ls -la

script: 
  - mvn clean package jacoco:report coveralls:report

after_success:
- bash <(curl -s https://codecov.io/bash)
