language: java
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8

sudo: false

env:
  global:
  - ENCRYPTION_LABEL: bf13b9e06e68
  - COMMIT_AUTHOR_EMAIL: antonisgor@gmail.com


script: mvn clean package jacoco:report coveralls:report

after_success:
  - bash <(curl -s https://codecov.io/bash)
