language: java
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8

sudo: false

before_install:
  - openssl aes-256-cbc -K $encrypted_bf13b9e06e68_key -iv $encrypted_bf13b9e06e68_iv -in deploykeySEiP.enc -out ~\/.ssh/deploykeySEiP -d

script: mvn clean package jacoco:report coveralls:report

after_success:
  - bash <(curl -s https://codecov.io/bash)
